### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by Mikolaj** [Mikolaj/horde-ad#2]
Last minute _optional_ breaking changes:
- [ ] hlint (M-x haskell-check | hlint . | C-x `)
- [ ] remove dead code detected with weeder or HPC

Last minute _optional_ checks and tweaks:
- [ ] compare current small benchmark results in CI vs CI benchmark logs from the previous release
- [ ] run long benchmarks and benchmarks against other libraries
- [ ] profile and optimize any surprise regressions and outliers
- [ ] spellcheck any longer texts
- [ ] verify that code samples in README and elsewhere make sense and match their counterparts in current tests

Testing:
- [ ] rebuild with `-fwith_expensive_assertions`
- [ ] run the full test suite (not the short CI one)
- [ ] review the output of CI for any red flags

Package:
- [ ] switch on the `release` flag in .cabal file
- [ ] check that haddocks get generated and fix any warnings
- [ ] update changelog
- [ ] if breaking changes, bump version number some more 
- [ ] verify no dependencies are too strict
- [ ] cabal check; cabal sdist
- [ ] upload hackage candidates
- [ ] create a draft of the github release
- [ ] flesh out the github release, copy the changelog
- [ ] publish the github release, which also creates a tag
- [ ] publish hackage candidates as the official releases

Supervise:
- [ ] if the haddocs don't build, upload them 
- [ ] https://matrix.hackage.haskell.org/package/horde-ad

Cool down:
- [ ] bump version number for development
- [ ] switch off `release` flag
